name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # به‌روزرسانی به نسخه 4

      - name: Build with Buildozer
        # استفاده از اکشن رسمی و معتبرتر
        uses: pypa/buildozer-action@v1 
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        # به‌روزرسانی به نسخه 4 برای رفع ارور Deprecation
        uses: actions/upload-artifact@v4 
        with:
          name: DietApp-Installer
          path: bin/*.apk
